DROP TABLE IF EXISTS BSAD_C;

CREATE TABLE BSAD_C AS(
SELECT
    ROW_NUMBER() OVER(PARTITION BY BSAD.MANDT, BSAD.BUKRS , BSAD.BELNR, BSAD.GJAHR, BSAD.BUZEI ORDER BY BSAD.MANDT, BSAD.BUKRS , BSAD.BELNR, BSAD.GJAHR, BSAD.BUZEI, BSAD._CELONIS_CHANGE_DATE DESC) AS NUM
	,BSAD.*
FROM "BSAD" AS BSAD ORDER BY NUM DESC
);

DELETE FROM BSAD_C WHERE NUM > 1;
