INSERT INTO "_CEL_O2C_ACTIVITIES" (
	"_CASE_KEY",
	"ACTIVITY_DE",
    "ACTIVITY_DETAIL_DE",
	"ACTIVITY_EN",
    "ACTIVITY_DETAIL_EN",
	"EVENTTIME",
	"_SORTING",
	"USER_NAME",
	"USER_TYPE",
	"MANDT",
	"VBELN",
	"POSNR",
    "_ACTIVITY_KEY")
SELECT DISTINCT
	 "VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
	,'Erstelle Warensendung' AS "ACTIVITY_DE"
    ,'Warensendungspositionsnr.: ' || VTTP.MANDT || VTTP.TKNUM || VTTP.TPNUM AS "ACTIVITY_DETAIL_DE"
	,'Create Shipment' AS "ACTIVITY_EN"
    ,'Shipment Item ID: ' || VTTP.MANDT || VTTP.TKNUM || VTTP.TPNUM AS "ACTIVITY_DETAIL_EN"
    ,CAST(VTTP.ERDAT AS DATE) + CAST(VTTP.ERZET AS TIME) AS "EVENTTIME"
    ,71 AS "_SORTING"
	,VTTP.ERNAM AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,"VBFA".MANDT AS "MANDT"
	,"VBFA".VBELV AS "VBELN"
	,"VBFA".POSNV AS "POSNR"
    , VTTP.MANDT ||VTTP.TKNUM || VTTP.TPNUM AS "_ACTIVITY_KEY"
FROM
	O2C_VBFA_V AS VBFA 
	JOIN VBFA AS VBFA_SHIP ON 1=1
		AND VBFA_SHIP.MANDT = VBFA.MANDT
		AND VBFA_SHIP.VBELV = VBFA.VBELN
        AND VBFA_SHIP.VBTYP_N = '8'
	JOIN VTTP AS VTTP ON 1=1
		AND VBFA_SHIP.MANDT = VTTP.MANDT
		AND VBFA_SHIP.VBELN = VTTP.TKNUM
		AND RIGHT(VBFA_SHIP.POSNN,4) = VTTP.TPNUM
	JOIN VTTK AS VTTK ON 1=1
		AND VTTK.MANDT = VTTP.MANDT
		AND VTTK.TKNUM = VTTP.TKNUM
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND VTTP.MANDT = USR02.MANDT
		AND VTTP.ERNAM = USR02.BNAME;