/*DESCRIPTION:
QPCD

*/
DROP VIEW IF EXISTS P2P_QPCD;

CREATE VIEW P2P_QPCD AS (
SELECT DISTINCT 
    QPCD.*,
    MAP."PRETTY_NAME", -- global job
    MAP."SC/PC", -- global job
    CAST(QPCD.GUELTIGAB AS DATE) AS TS_GUELTIGAB,
    CAST(QPCD.E_DATUM AS DATE) AS TS_E_DATUM,
   CAST(QPCD.A_DATUM AS DATE) AS TS_A_DATUM
FROM QALS as QALS
    inner join QAVE ON 1=1
        AND QAVE."SCHEMA" = QALS."SCHEMA" -- global job
		AND QAVE.MANDANT = QALS.MANDANT
		AND QAVE.PRUEFLOS = QALS.PRUEFLOS
  	INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
        AND QALS."SCHEMA" = CASES."SCHEMA" -- global job
		AND QALS.MANDANT = CASES.MANDT
		AND QALS.EBELN = CASES.EBELN
		AND QALS.EBELP = CASES.EBELP
 inner join QPCD as QPCD on 1=1
    AND QAVE."SCHEMA" = QPCD."SCHEMA" -- global job
    AND "QAVE"."MANDANT" = QPCD."MANDT"
    AND "QAVE".VCODEGRP = "QPCD"."CODEGRUPPE"
    AND "QAVE".VCODE = "QPCD"."CODE"
    AND "QAVE"."VERSIONCD" = "QPCD"."VERSION"
    AND "QAVE"."VKATART" = "QPCD"."KATALOGART"
	INNER JOIN "SCHEMA_xlsx_MD" AS MAP ON 1=1 -- global job
    and QPCD."SCHEMA" = MAP."SCHEMA"
);




