/*DESCRIPTION:
1. Transformation Description:
This transformation creates the following activities: Refuse Purchase Requisition, Release Purchase Requisition

















2. Required Tables:
CDHDR
CDPOS
EBAN
TMP_P2P_EKKO_EKPO
USR02

3. Required Columns:
CDHDR.BLOCKPRINDICATORS
CDHDR.CHANGENR
CDHDR.MANDANT
CDHDR.RELEASEPRINDICATORS
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDPOS.CHANGENR
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTCLAS
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
CDPOS.VALUE_OLD
EBAN.BANFN
EBAN.BNFPO
EBAN.MANDT
TMP_P2P_EKKO_EKPO.BANFN
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME

5. Parameters used in where clause:
releasePrIndicators
blockPrIndicators

6. Parameters used in joins:
None
*/
--************************ PIN 020 Logic *************************************
INSERT INTO _CEL_P2P_ACTIVITIES(
    "SCHEMA", -- global job
    "PRETTY_NAME", -- global job
    "SC/PC", -- global job
    "_CASE_KEY"
    ,"MANDT"
	,"EBELN"
	,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
    "E"."SCHEMA" as "SCHEMA" -- global job
    ,"E"."PRETTY_NAME" -- global job
    ,E."SC/PC" -- global job
	,E._CASE_KEY AS "_CASE_KEY"
    ,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN 'Lehne BANF ab'
        WHEN CDPOS.VALUE_NEW = 'F' THEN 'Gebe BANF frei' 
    END AS "ACTIVITY_DE"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN 'Refuse Purchase Requisition'
        WHEN CDPOS.VALUE_NEW = 'F'  THEN 'Release Purchase Requisition' 
    END AS "ACTIVITY_EN"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN CAST(CDHDR_BANPR.UDATE AS DATE) + CAST(CDHDR_BANPR.UTIME AS TIME)
        WHEN CDPOS.VALUE_NEW = 'F'  THEN CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME)
    END AS "EVENTTIME"
    ,CASE 
		WHEN CDPOS.VALUE_NEW = 'S' AND CDPOS_BANPR.VALUE_NEW = '08' THEN 300
        WHEN CDPOS.VALUE_NEW = 'F' THEN 400	
	END AS "_SORTING"
    ,CDHDR.USERNAME AS "USER_NAME"
    ,USR02.USTYP AS "USER_TYPE"
    ,CDPOS.TABNAME AS "CHANGED_TABLE"
    ,CDPOS.FNAME AS "CHANGED_FIELD"
    ,CDPOS.VALUE_OLD AS "CHANGED_FROM"
    ,CDPOS.VALUE_NEW AS "CHANGED_TO"
    ,CDPOS.CHANGENR AS "CHANGE_NUMBER"
    ,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,E."PRETTY_NAME"||CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY" -- global job
FROM 
    TMP_P2P_EKKO_EKPO AS E 
    JOIN CDPOS AS CDPOS ON
        CDPOS."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS.MANDANT = E.MANDT AND
        CDPOS.TABKEY = E."TABKEY_EBAN" AND
        "CDPOS"."FNAME" = 'FRGKZ'
    JOIN CDHDR AS CDHDR ON
        CDPOS."SCHEMA" = CDHDR."SCHEMA" AND -- global job
        CDPOS.MANDANT = CDHDR.MANDANT AND
        CDPOS.CHANGENR = CDHDR.CHANGENR
    JOIN EBAN AS EBAN ON 
        E."SCHEMA" = EBAN."SCHEMA" AND -- global job 
        E.MANDT = EBAN.MANDT AND
        E.BANFN = EBAN.BANFN AND
        E.BNFPO = EBAN.BNFPO
    LEFT JOIN USR02 AS USR02 ON
        CDHDR."SCHEMA" = USR02."SCHEMA" AND -- global job
		CDHDR.MANDANT = USR02.MANDT AND
		CDHDR.USERNAME = USR02.BNAME
    LEFT JOIN CDPOS AS CDPOS_BANPR ON
        CDPOS_BANPR."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS_BANPR.MANDANT = E.MANDT AND
        CDPOS_BANPR.TABKEY = E."TABKEY_EBAN" AND
        "CDPOS_BANPR"."FNAME" = 'BANPR'
    JOIN CDHDR AS CDHDR_BANPR ON 
        CDPOS_BANPR."SCHEMA" = CDHDR_BANPR."SCHEMA" AND -- global job
        CDPOS_BANPR.MANDANT = CDHDR_BANPR.MANDANT AND
        CDPOS_BANPR.CHANGENR = CDHDR_BANPR.CHANGENR
WHERE
    "E"."PRETTY_NAME" = 'PIN020' AND
    CDPOS.OBJECTCLAS = 'BANF' AND
    CDPOS.VALUE_NEW IN ('S', 'F')
   -- as temp WHERE temp._Sorting ='300' and temp.EBELN = '1004898520'
    -- CDPOS.FNAME =  'FRGKZ' AND 
    -- CDPOS_BANPR.FNAME = 'BANPR' --AND
;

--************************ PS1XXX + PSG048 Logic *************************************
INSERT INTO _CEL_P2P_ACTIVITIES(
    "SCHEMA", -- global job
    "PRETTY_NAME", -- global job
    "SC/PC", -- global job
    "_CASE_KEY"
    ,"MANDT"
	,"EBELN"
	,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
    "E"."SCHEMA" as "SCHEMA" -- global job
    ,"E"."PRETTY_NAME" -- global job
    ,E."SC/PC" -- global job
	,E._CASE_KEY AS "_CASE_KEY"
    ,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'X' THEN 'Lehne BANF ab'
        WHEN CDPOS.VALUE_NEW = 'E' THEN 'Gebe BANF frei' 
    END AS "ACTIVITY_DE"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'X' THEN 'Refuse Purchase Requisition'
        WHEN CDPOS.VALUE_NEW = 'E'  THEN 'Release Purchase Requisition' 
    END AS "ACTIVITY_EN"
    ,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS "EVENTTIME"
    ,CASE 
		WHEN CDPOS.VALUE_NEW = 'X' THEN 300
        WHEN CDPOS.VALUE_NEW = 'E' THEN 400	
	END AS "_SORTING"
    ,CDHDR.USERNAME AS "USER_NAME"
    ,USR02.USTYP AS "USER_TYPE"
    ,CDPOS.TABNAME AS "CHANGED_TABLE"
    ,CDPOS.FNAME AS "CHANGED_FIELD"
    ,CDPOS.VALUE_OLD AS "CHANGED_FROM"
    ,CDPOS.VALUE_NEW AS "CHANGED_TO"
    ,CDPOS.CHANGENR AS "CHANGE_NUMBER"
    ,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,E."PRETTY_NAME"||CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY" -- global job
FROM 
    TMP_P2P_EKKO_EKPO AS E 
    JOIN CDPOS AS CDPOS ON
        CDPOS."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS.MANDANT = E.MANDT AND
        CDPOS.TABKEY = E."TABKEY_EBAN"
    JOIN CDHDR AS CDHDR ON
        CDPOS."SCHEMA" = CDHDR."SCHEMA" AND -- global job
        CDPOS.MANDANT = CDHDR.MANDANT AND
        CDPOS.CHANGENR = CDHDR.CHANGENR
    INNER JOIN EBAN AS EBAN ON 
        E."SCHEMA" = EBAN."SCHEMA" AND -- global job 
        E.MANDT = EBAN.MANDT AND
        E.BANFN = EBAN.BANFN AND
        E.BNFPO = EBAN.BNFPO
    LEFT JOIN USR02 AS USR02 ON
        CDHDR."SCHEMA" = USR02."SCHEMA" AND -- global job
		CDHDR.MANDANT = USR02.MANDT AND
		CDHDR.USERNAME = USR02.BNAME
WHERE
    "E"."PRETTY_NAME" IN  ('PS1007','PS1030', 'PS1032', 'PS1035', 'PS1036', 'PS1038', 'PS1039', 'PS1040', 'PS1044', 'PSG048') AND
    CDPOS.OBJECTCLAS = 'BANF' AND
    CDPOS.FNAME = 'FRGKZ' AND
    CDPOS.VALUE_NEW IN ( 'X', 'E')
    --(CDPOS.VALUE_NEW IN <%=blockPrIndicators%> OR CDPOS.VALUE_NEW IN <%=releasePrIndicators%>)
;

--************************ PP2 005 Logic *************************************
INSERT INTO _CEL_P2P_ACTIVITIES(
    "SCHEMA", -- global job
    "PRETTY_NAME", -- global job
    "SC/PC", -- global job
    "_CASE_KEY"
    ,"MANDT"
	,"EBELN"
	,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
    "E"."SCHEMA" as "SCHEMA" -- global job
    ,"E"."PRETTY_NAME" -- global job
    ,E."SC/PC" -- global job
	,E._CASE_KEY AS "_CASE_KEY"
    ,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN 'Lehne BANF ab'
        WHEN CDPOS.VALUE_NEW = 'R' THEN 'Gebe BANF frei' 
    END AS "ACTIVITY_DE"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN 'Refuse Purchase Requisition'
        WHEN CDPOS.VALUE_NEW = 'R'  THEN 'Release Purchase Requisition' 
    END AS "ACTIVITY_EN"
    ,CASE 
        WHEN CDPOS.VALUE_NEW = 'S'  AND CDPOS_BANPR.VALUE_NEW = '08' THEN CAST(CDHDR_BANPR.UDATE AS DATE) + CAST(CDHDR_BANPR.UTIME AS TIME)
        WHEN CDPOS.VALUE_NEW = 'R'  THEN CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME)
    END AS "EVENTTIME"
    ,CASE 
		WHEN CDPOS.VALUE_NEW = 'S' AND CDPOS_BANPR.VALUE_NEW = '08' THEN 300
        WHEN CDPOS.VALUE_NEW = 'R' THEN 400	
	END AS "_SORTING"
    ,CDHDR.USERNAME AS "USER_NAME"
    ,USR02.USTYP AS "USER_TYPE"
    ,CDPOS.TABNAME AS "CHANGED_TABLE"
    ,CDPOS.FNAME AS "CHANGED_FIELD"
    ,CDPOS.VALUE_OLD AS "CHANGED_FROM"
    ,CDPOS.VALUE_NEW AS "CHANGED_TO"
    ,CDPOS.CHANGENR AS "CHANGE_NUMBER"
    ,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,E."PRETTY_NAME"||CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY" -- global job
FROM 
    TMP_P2P_EKKO_EKPO AS E 
    JOIN CDPOS AS CDPOS ON
        CDPOS."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS.MANDANT = E.MANDT AND
        CDPOS.TABKEY = E."TABKEY_EBAN" AND
        "CDPOS"."FNAME" = 'FRGKZ'
    JOIN CDHDR AS CDHDR ON
        CDPOS."SCHEMA" = CDHDR."SCHEMA" AND -- global job
        CDPOS.MANDANT = CDHDR.MANDANT AND
        CDPOS.CHANGENR = CDHDR.CHANGENR
    JOIN EBAN AS EBAN ON 
        E."SCHEMA" = EBAN."SCHEMA" AND -- global job 
        E.MANDT = EBAN.MANDT AND
        E.BANFN = EBAN.BANFN AND
        E.BNFPO = EBAN.BNFPO
    LEFT JOIN USR02 AS USR02 ON
        CDHDR."SCHEMA" = USR02."SCHEMA" AND -- global job
		CDHDR.MANDANT = USR02.MANDT AND
		CDHDR.USERNAME = USR02.BNAME
    LEFT JOIN CDPOS AS CDPOS_BANPR ON
        CDPOS_BANPR."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS_BANPR.MANDANT = E.MANDT AND
        CDPOS_BANPR.TABKEY = E."TABKEY_EBAN" AND
        "CDPOS_BANPR"."FNAME" = 'BANPR'
    JOIN CDHDR AS CDHDR_BANPR ON 
        CDPOS_BANPR."SCHEMA" = CDHDR_BANPR."SCHEMA" AND -- global job
        CDPOS_BANPR.MANDANT = CDHDR_BANPR.MANDANT AND
        CDPOS_BANPR.CHANGENR = CDHDR_BANPR.CHANGENR
WHERE
    "E"."PRETTY_NAME" = 'PP2005' AND
    CDPOS.OBJECTCLAS = 'BANF' AND
    CDPOS.VALUE_NEW IN ('R', 'S') 
   -- as temp WHERE temp._Sorting ='300' and temp.EBELN = '1004898520'
    -- CDPOS.FNAME =  'FRGKZ' AND 
    -- CDPOS_BANPR.FNAME = 'BANPR' --AND
;

--************************ PP1011 Logic *************************************
INSERT INTO _CEL_P2P_ACTIVITIES(
    "SCHEMA", -- global job
    "PRETTY_NAME", -- global job
    "SC/PC", -- global job
    "_CASE_KEY"
    ,"MANDT"
	,"EBELN"
	,"EBELP"
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"CHANGED_TABLE"
    ,"CHANGED_FIELD"
    ,"CHANGED_FROM"
    ,"CHANGED_TO"
    ,"CHANGE_NUMBER"
    ,"TRANSACTION_CODE"
    ,"_ACTIVITY_KEY")
SELECT DISTINCT
    "E"."SCHEMA" as "SCHEMA" -- global job
    ,"E"."PRETTY_NAME" -- global job
    ,E."SC/PC" -- global job
	,E._CASE_KEY AS "_CASE_KEY"
    ,E.MANDT AS "MANDT"
	,E.EBELN AS "EBELN"
	,E.EBELP AS "EBELP"
    ,CASE 
    --    WHEN CDPOS.VALUE_NEW = 'X' THEN 'Lehne BANF ab'
        WHEN CDPOS.VALUE_NEW = '2' THEN 'Gebe BANF frei' 
    END AS "ACTIVITY_DE"
    ,CASE 
    --   WHEN CDPOS.VALUE_NEW = 'X' THEN 'Refuse Purchase Requisition'
        WHEN CDPOS.VALUE_NEW = '2'  THEN 'Release Purchase Requisition' 
    END AS "ACTIVITY_EN"
    ,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS "EVENTTIME"
    ,CASE 
	--	WHEN CDPOS.VALUE_NEW = 'X' THEN 300
        WHEN CDPOS.VALUE_NEW = '2' THEN 400	
	END AS "_SORTING"
    ,CDHDR.USERNAME AS "USER_NAME"
    ,USR02.USTYP AS "USER_TYPE"
    ,CDPOS.TABNAME AS "CHANGED_TABLE"
    ,CDPOS.FNAME AS "CHANGED_FIELD"
    ,CDPOS.VALUE_OLD AS "CHANGED_FROM"
    ,CDPOS.VALUE_NEW AS "CHANGED_TO"
    ,CDPOS.CHANGENR AS "CHANGE_NUMBER"
    ,CDHDR.TCODE AS "TRANSACTION_CODE"
    ,E."PRETTY_NAME"||CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY" -- global job
FROM 
    TMP_P2P_EKKO_EKPO AS E 
    JOIN CDPOS AS CDPOS ON
        CDPOS."SCHEMA" = E."SCHEMA" AND -- global job
        CDPOS.MANDANT = E.MANDT AND
        CDPOS.TABKEY = E."TABKEY_EBAN"
    JOIN CDHDR AS CDHDR ON
        CDPOS."SCHEMA" = CDHDR."SCHEMA" AND -- global job
        CDPOS.MANDANT = CDHDR.MANDANT AND
        CDPOS.CHANGENR = CDHDR.CHANGENR
    INNER JOIN EBAN AS EBAN ON 
        E."SCHEMA" = EBAN."SCHEMA" AND -- global job 
        E.MANDT = EBAN.MANDT AND
        E.BANFN = EBAN.BANFN AND
        E.BNFPO = EBAN.BNFPO
    LEFT JOIN USR02 AS USR02 ON
        CDHDR."SCHEMA" = USR02."SCHEMA" AND -- global job
		CDHDR.MANDANT = USR02.MANDT AND
		CDHDR.USERNAME = USR02.BNAME
WHERE
    "E"."PRETTY_NAME" IN  ('PP2005') AND
    CDPOS.OBJECTCLAS = 'BANF' AND
    CDPOS.FNAME = 'FRGKZ' AND
    CDPOS.VALUE_NEW IN ( '2')
    --(CDPOS.VALUE_NEW IN <%=blockPrIndicators%> OR CDPOS.VALUE_NEW IN <%=releasePrIndicators%>)
;