/*DESCRIPTION:
QPGR
*/
DROP VIEW IF EXISTS P2P_QPGR;

CREATE VIEW P2P_QPGR AS (
SELECT DISTINCT 
    QPGR.*,
    MAP."PRETTY_NAME", -- global job
    MAP."SC/PC", -- global job
   CAST(QPGR.E_DATUM AS DATE) AS TS_E_DATUM,
   CAST(QPGR.A_DATUM AS DATE) AS TS_A_DATUM
FROM QALS as QALS
    inner join QAVE ON 1=1
        AND QAVE."SCHEMA" = QALS."SCHEMA" -- global job
		AND QAVE.MANDANT = QALS.MANDANT
		AND QAVE.PRUEFLOS = QALS.PRUEFLOS
  	INNER JOIN _CEL_P2P_CASES AS CASES ON 1=1
        AND QALS."SCHEMA" = CASES."SCHEMA" -- global job
		AND QALS.MANDANT = CASES.MANDT
		AND QALS.EBELN = CASES.EBELN
		AND QALS.EBELP = CASES.EBELP
 inner join QPGR as QPGR on 1=1
    AND QAVE."SCHEMA" = QPGR."SCHEMA" -- global job
    AND "QAVE"."MANDANT" = QPGR."MANDT"
    AND "QAVE".VCODEGRP = "QPGR"."CODEGRUPPE"
    AND "QAVE"."VKATART" = "QPGR"."KATALOGART"
	INNER JOIN "SCHEMA_xlsx_MD" AS MAP ON 1=1 -- global job
    and QPGR."SCHEMA" = MAP."SCHEMA"
);




