DROP VIEW IF EXISTS WM_LTAK;

CREATE VIEW WM_LTAK AS 
SELECT DISTINCT 
    LTAK.SCHEMA -- global job
    , MAP.PRETTY_NAME -- global job
    , MAP.PRETTY_NAME || LTAK.MANDT || LTAK.LGNUM || LTAK.TANUM || LTAP.TAPOS AS "_CASE_KEY" -- global job
    , LTAK.MANDT
    , LTAK.LGNUM
    , T300T.LNUMT
    , LTAK.TANUM
    , LTAK.BWART
    , LTAK.BWLVS
    , LTAK.TBPRI
    , LTAK.TRART
    , LTAK.BDATU
    , LTAK.BZEIT
    , LTAK.BNAME
    , LTAK.REFNR
    , LTAK.TBNUM
    , LTAK.UBNUM
    , LTAK.VBELN
    , LTAK.KQUIT
    , LTAK.QDATU AS QDATEHEAD
    , LTAK.MBLNR
    , LTAK.MJAHR
    , LTAK.BETYP
    , LTAK.BENUM
    , LTAK.DRUKZ
    , LTAK.DRUCK
    , LTAK.TEILK
    , LTAK.KR2SO
    , LTAK.KR2KU
    , LTAK.KDISO
    , LTAK.KZPLA
    , LTAK.PLDAT
    , LTAK.RSNUM
    , LTAK.LZNUM
    , LTAK.BDART
    , LTAK.PKNUM
    , LTAK.PKPOS
    , LTAK.KZLEI
    , LTAK.KISTZ
    , LTAK.KISTP
    , LTAK.PERNR
    , LTAK.SOLWM
    , LTAK.SOLEX
    , LTAK.ISTWM
    , LTAK.ZEIEI
    , LTAK.HRSTS
    , LTAK.STDAT
    , LTAK.ENDAT
    , LTAK.STUZT
    , LTAK.ENUZT
    , LTAK.L2SKA
    , LTAK.MINWM
    , LTAK.LGTOR
    , LTAK.LGBZO
    , LTAK.KZVEP
    , LTAK.SWABW
    , LTAK.AUSFB
    , LTAK.SPEZI
    , LTAK.VBTYP
    , LTAK.QUEUE
    , LTAK.KGVNQ
    , LTAK.TAPRI
    , LTAK.KVQUI
    , LTAK.HUCON
    , LTAK.NOITM
    , LTAK.KZTRM
    , LTAK.LATER
    , LTAK.PASSD
    , LTAK.MULTL
FROM 
    LTAK AS LTAK
    JOIN LTAP AS LTAP ON 1=1
        AND LTAK."SCHEMA" = LTAP."SCHEMA" -- global job
        AND LTAK.MANDT = LTAP.MANDT
        AND LTAK.LGNUM = LTAP.LGNUM
        AND LTAK.TANUM = LTAP.TANUM
    LEFT JOIN T300T AS T300T ON 1=1
        AND T300T."SCHEMA" = LTAK."SCHEMA" -- global job
        AND T300T.MANDT = LTAK.MANDT
        AND T300T.LGNUM = LTAK.LGNUM
        AND T300T.SPRAS = '<%=primaryLanguageKey%>'
    JOIN "SCHEMA_XLSX_MD" AS "MAP" ON
        LTAK."SCHEMA" = "MAP"."SCHEMA"
;