-- Statement: Activity: Create Material Document

INSERT INTO _CEL_WM_ACTIVITIES (
     "SCHEMA"
    ,"PRETTY_NAME"
	,"_CASE_KEY"
    ,"MANDT"
    ,"LGNUM"
    ,"TANUM"
    ,"TAPOS" 
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_CELONIS_CHANGE_DATE"
)
SELECT
    WMTO.SCHEMA AS "SCHEMA"
    , MAP.PRETTY_NAME AS "PRETTY_NAME"
	, WMTO._CASE_KEY AS "_CASE_KEY"
    , WMTO.MANDT AS "MANDT"
    , WMTO.LGNUM AS "LGNUM"
    , WMTO.TANUM AS "TANUM"
    , WMTO.TAPOS AS "TAPOS" 
    ,'Erstelle Materialbeleg' AS "ACTIVITY_DE"
	,'Create Material Document' AS "ACTIVITY_EN"
	, CAST(MKPF.CPUDT AS DATE) + CAST(MKPF.CPUTM AS TIME) AS "EVENTTIME"
    , 50 AS "_SORTING"
    , MKPF.USNAM AS "USER_NAME"
    , USR02.USTYP AS "USER_TYPE"
    , NOW() AS "_CELONIS_CHANGE_DATE"
FROM TMP_WM_LTAK_LTAP AS WMTO
JOIN MSEG AS MSEG ON 1 = 1
    AND MSEG.SCHEMA = WMTO.SCHEMA
    AND MSEG.MANDT = WMTO.MANDT
    AND MSEG.MBLNR = WMTO.MBLNR
    AND MSEG.MJAHR = WMTO.MJAHR
    AND MSEG.ZEILE = WMTO.MBPOS
JOIN MKPF AS MKPF ON 1=1
    AND MKPF.SCHEMA = MSEG.SCHEMA
    AND MKPF.MANDT = MSEG.MANDT
    AND MKPF.MBLNR = MSEG.MBLNR
    AND MKPF.MJAHR = MSEG.MJAHR
LEFT JOIN USR02 AS USR02 ON 1=1
    AND MKPF."SCHEMA" = USR02."SCHEMA" -- global job
    AND MKPF.MANDT = USR02.MANDT
    AND MKPF.USNAM = USR02.BNAME
JOIN "SCHEMA_XLSX_MD" AS MAP ON
    MAP.SCHEMA = WMTO.SCHEMA 
;