-- Statement: Activity: Begin Quality Inspection

INSERT INTO _CEL_WM_ACTIVITIES (
     "SCHEMA"
    ,"PRETTY_NAME"
	,"_CASE_KEY"
    ,"MANDT"
    ,"LGNUM"
    ,"TANUM"
    ,"TAPOS" 
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_CELONIS_CHANGE_DATE"
)
SELECT
    WMTO.SCHEMA AS "SCHEMA"
    , MAP.PRETTY_NAME AS "PRETTY_NAME"
	, WMTO._CASE_KEY AS "_CASE_KEY"
    , WMTO.MANDT AS "MANDT"
    , WMTO.LGNUM AS "LGNUM"
    , WMTO.TANUM AS "TANUM"
    , WMTO.TAPOS AS "TAPOS" 
    ,'Qualitätsprüfung Beginn' AS "ACTIVITY_DE"
	,'Begin Quality Inspection' AS "ACTIVITY_EN"
	,CASE 
        WHEN CAST("QALS"."PASTRTERM" AS DATE) IS NULL OR CAST(QALS.PASTRZEIT as TIME) = '00:00:00'
        THEN CAST(QALS.ERSTELDAT AS DATE) + CAST(QALS.ERSTELZEIT AS TIME)                       
        ELSE CAST(QALS.PASTRTERM AS DATE) + CAST(QALS.PASTRZEIT AS TIME) 
     END AS "EVENTTIME"
    , 500 AS  "_SORTING"
    , QALS.ERSTELLER AS "USER_NAME"
    , USR02.USTYP AS "USER_TYPE"
    , NOW() AS "_CELONIS_CHANGE_DATE"
FROM TMP_WM_LTAK_LTAP AS WMTO
JOIN QALS as QALS on 1=1
    AND QALS."SCHEMA" = WMTO."SCHEMA" -- global job
    AND QALS.MANDANT = WMTO.MANDT
    AND QALS.PRUEFLOS = WMTO.QPLOS		
LEFT JOIN USR02 AS USR02 ON 1=1
    AND QALS."SCHEMA" = USR02."SCHEMA" -- global job
    AND QALS.MANDANT = USR02.MANDT
    AND QALS.ERSTELLER = USR02.BNAME
JOIN "SCHEMA_XLSX_MD" AS MAP ON
    MAP.SCHEMA = WMTO.SCHEMA 
;

-- Statement: Activity: Quality Decision

INSERT INTO _CEL_WM_ACTIVITIES (
     "SCHEMA"
    ,"PRETTY_NAME"
	,"_CASE_KEY"
    ,"MANDT"
    ,"LGNUM"
    ,"TANUM"
    ,"TAPOS" 
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_CELONIS_CHANGE_DATE"
)
SELECT
    WMTO.SCHEMA AS "SCHEMA"
    , MAP.PRETTY_NAME AS "PRETTY_NAME"
	, WMTO._CASE_KEY AS "_CASE_KEY"
    , WMTO.MANDT AS "MANDT"
    , WMTO.LGNUM AS "LGNUM"
    , WMTO.TANUM AS "TANUM"
    , WMTO.TAPOS AS "TAPOS" 
    , CASE 
        WHEN Q.VBEWERTUNG = 'A' THEN 'Qualität: Akzeptiert' 
        WHEN Q.VBEWERTUNG = 'R' THEN 'Qualität: Abgelehnt' 
        ELSE 'Qualität: Nicht bewertet' 
      END AS "ACTIVITY_DE"
    , CASE 
        WHEN Q.VBEWERTUNG = 'A' THEN 'Quality: Accepted' 
        WHEN Q.VBEWERTUNG = 'R' THEN 'Quality: Rejected' 
        ELSE 'Quality: Not evaluated'
      END AS "ACTIVITY_EN"
	, CAST(Q.VDATUM AS DATE) + CAST(Q.VEZEITERF AS TIME) AS "EVENTTIME"
    , 550 AS  "_SORTING"
    , Q.VNAME AS "USER_NAME"
    , USR02.USTYP AS "USER_TYPE"
    , NOW() AS "_CELONIS_CHANGE_DATE"
FROM TMP_WM_LTAK_LTAP AS WMTO
JOIN QALS as QALS on 1=1
    AND QALS."SCHEMA" = WMTO."SCHEMA" -- global job
    AND QALS.MANDANT = WMTO.MANDT
    AND QALS.PRUEFLOS = WMTO.QPLOA		
JOIN QAVE as Q on 1=1 
    AND Q."SCHEMA" = QALS."SCHEMA" -- global job
    AND Q.MANDANT = QALS.MANDANT
    AND Q.PRUEFLOS	= QALS.PRUEFLOS
LEFT JOIN USR02 AS USR02 ON 1=1
    AND Q."SCHEMA" = USR02."SCHEMA" -- global job
    AND Q.MANDANT = USR02.MANDT
    AND Q.VNAME = USR02.BNAME
JOIN "SCHEMA_XLSX_MD" AS MAP ON
    MAP.SCHEMA = WMTO.SCHEMA;