DROP VIEW IF EXISTS WM_MARC;

CREATE VIEW WM_MARC AS 
SELECT DISTINCT 
  MAP."PRETTY_NAME",
  MARC.*
 FROM 
    MARC 
    JOIN "SCHEMA_XLSX_MD" AS "MAP" ON
        MARC."SCHEMA" = "MAP"."SCHEMA"
;