INSERT INTO _CEL_WM_ACTIVITIES (
     "SCHEMA"
    ,"PRETTY_NAME"
	,"_CASE_KEY"
    ,"MANDT"
    ,"LGNUM"
    ,"TANUM"
    ,"TAPOS" 
    ,"ACTIVITY_DE"
    ,"ACTIVITY_EN"
    ,"EVENTTIME"
    ,"_SORTING"
    ,"USER_NAME"
    ,"USER_TYPE"
    ,"_CELONIS_CHANGE_DATE"
)
SELECT DISTINCT
	 WMTO.SCHEMA AS "SCHEMA"
    , MAP.PRETTY_NAME AS "PRETTY_NAME"
	, WMTO._CASE_KEY AS "_CASE_KEY"
    , WMTO.MANDT AS "MANDT"
    , WMTO.LGNUM AS "LGNUM"
    , WMTO.TANUM AS "TANUM"
    , WMTO.TAPOS AS "TAPOS" 
	, 'Lege Transportbedarfsposition an' AS "ACTIVITY_DE"
	, 'Create Transfer Requirement Item' AS "ACTIVITY_EN"
	, CAST(LTBK.BDATU AS DATE) + CAST(LTBK.BZEIT AS TIME) AS "EVENTTIME"
	, 100 AS "_SORTING"
	, LTBK.BNAME AS "USER_NAME"
	, USR02.USTYP AS "USER_TYPE"
    , NOW() AS "_CELONIS_CHANGE_DATE"
FROM TMP_WM_LTAK_LTAP AS WMTO
    JOIN LTBP AS LTBP ON
		LTBP.SCHEMA = WMTO.SCHEMA
        AND LTBP.MANDT = WMTO.MANDT
		AND LTBP.LGNUM = WMTO.LGNUM 
		AND LTBP.TBNUM = WMTO.TBNUM
		AND LTBP.TBPOS = WMTO.TBPOS
    JOIN LTBK AS LTBK ON
        LTBK.SCHEMA = LTBP.SCHEMA
        AND LTBK.MANDT = LTBP.MANDT
        AND LTBP.LGNUM = WMTO.LGNUM
        AND LTBK.TBNUM = WMTO.TBNUM
	LEFT JOIN USR02 AS USR02 ON
        LTBK.SCHEMA = USR02.SCHEMA
		AND LTBK.MANDT = USR02.MANDT
		AND LTBK.BNAME = USR02.BNAME
    JOIN "SCHEMA_XLSX_MD" AS MAP ON
        MAP.SCHEMA = WMTO.SCHEMA
;