DROP VIEW IF EXISTS WM_LTAP;

CREATE VIEW WM_LTAP AS 
SELECT DISTINCT
    LTAP."SCHEMA" -- global job
    , MAP."PRETTY_NAME" -- global job
	, MAP."PRETTY_NAME"||LTAP.MANDT || LTAP.LGNUM || LTAP.TANUM || LTAP.TAPOS AS _CASE_KEY -- global job anpassung System includiert
    , LTAP.MANDT
    , LTAP.LGNUM
    , T300T.LNUMT AS "LGNUM_TEXT"
    , LTAP.TANUM
    , LTAP.TAPOS
    , LTAP.TBPOS
    , LTAP.POSNR
    , LTAP.MATNR
    , LTAP.WERKS
    , LTAP.CHARG
    , LTAP.BESTQ
    , LTAP.SOBKZ
    , LTAP.SONUM
    , LTAP.STOFF
    , LTAP.MEINS
    , LTAP.ALTME
    , LTAP.UMREZ
    , LTAP.UMREN
    , LTAP.LETYP
    , LTAP.KZFEH
    , LTAP.LANUM
    , LTAP.KZQUI
    , LTAP.KZNKO
    , LTAP.NULKO
    , LTAP.KZINV
    , LTAP.IVNUM
    , LTAP.PQUIT
    , LTAP.QDATU
    , LTAP.QZEIT
    , LTAP.QNAME
    , LTAP.BRGEW
    , LTAP.GEWEI
    , LTAP.MBPOS
    , LTAP.WEMPF
    , LTAP.ABLAD
    , LTAP.WDATU
    , LTAP.WENUM
    , LTAP.WEPOS
    , LTAP.ZEUGN
    , LTAP.LDEST
    , LTAP.VORGA
    , LTAP.VLTYP
    , T301T_VON.LTYPT AS "VLTYP_TEXT"
    , LTAP.VLBER
    , T302T_VON.LBERT AS "VLBER_TEXT"
    , LTAP.VLPLA
    , LTAP.VKDYN
    , LTAP.VPPOS
    , LTAP.VANZL
    , LTAP.VANBR
    , LTAP.VSOLM
    , LTAP.VISTM
    , LTAP.VDIFM
    , LTAP.VSOLA
    , LTAP.VISTA
    , LTAP.VDIFA
    , LTAP.VLQNR
    , LTAP.VAPPC
    , LTAP.NLTYP
    , T301T_NACH.LTYPT AS "NLTYP_TEXT"
    , LTAP.NLBER
    , T302T_NACH.LBERT AS "NLBER_TEXT"
    , LTAP.NLPLA
    , LTAP.NKDYN
    , LTAP.NPPOS
    , LTAP.NANZL
    , LTAP.NANBR
    , LTAP.NSOLM
    , LTAP.NISTM
    , LTAP.NDIFM
    , LTAP.NSOLA
    , LTAP.NISTA
    , LTAP.NDIFA
    , LTAP.NLQNR
    , LTAP.NAPPC
    , LTAP.RLTYP
    , LTAP.RLBER
    , LTAP.RLPLA
    , LTAP.RPPOS
    , LTAP.RSOLM
    , LTAP.RISTM
    , LTAP.RDIFM
    , LTAP.RSOLA
    , LTAP.RISTA
    , LTAP.RDIFA
    , LTAP.RLQNR
    , LTAP.RAPPC
    , LTAP.DLTYP
    , LTAP.DLPLA
    , LTAP.DLQNR
    , LTAP.DMENG
    , LTAP.DMENA
    , LTAP.KZDIF
    , T336T.DTEXT AS "KZDIF_TEXT"
    , LTAP.MAKTX
    , LTAP.DRUCK
    , LTAP.VLENR
    , LTAP.NLENR
    , LTAP.DLENR
    , LTAP.VLEST
    , LTAP.NLEST
    , LTAP.LELAS
    , LTAP.HOMVE
    , LTAP.POSTY
    , LTAP.ORPOS
    , LTAP.VSUMM
    , LTAP.VBLCH
    , LTAP.NSUMM
    , LTAP.NBLCH
    , LTAP.RSPOS
    , LTAP.VFDAT
    , LTAP.VKAPV
    , LTAP.VKAPA
    , LTAP.NKAPA
    , LTAP.RKAPA
    , LTAP.KZSUB
    , LTAP.QPLOS
    , LTAP.QPLOA
    , LTAP.KZSTI
    , LTAP.RSART
    , LTAP.KZECH
    , LTAP.KOBER
    , LTAP.LGORT
    , LTAP.SOLPO
    , LTAP.ZEIEI
    , LTAP.L2SKR
    , LTAP.VOLUM
    , LTAP.VOLEH
    , LTAP.KZBEF
    , LTAP.IMREL
    , LTAP.NWIRM
    , LTAP.WIRME
    , LTAP.NPLEI
    , LTAP.KBNKZ
    , LTAP.STOAN
    , LTAP.KGVNQ
    , LTAP.PVQUI
    , LTAP.EDATU
    , LTAP.EZEIT
    , LTAP.ENAME
    , LTAP.KZFME
    , LTAP.QUSUB
    , LTAP.FHUTA
    , LTAP.VNEST
    , LTAP.VHILM
    , LTAP.VDUMM
    , LTAP.NDUMM
    , LTAP.VSERI
    , LTAP.HUPIK
    , LTAP.NXIDV
    , LTAP.NOLIS
    , LTAP.NPIPO
    , LTAP.PIPAR
    , LTAP.PCKPF
    , LTAP.KZTRM
    , LTAP.PASSD
    , LTAP.VBELN
    , LTAP.KZXDK
    , LTAP.KZVAS
    , LTAP.DCNUM
    , LTAP.ZRSTG
    , LTAP.TOVAS
FROM 
    LTAP AS LTAP
    JOIN LTAK AS LTAK ON 1=1
        AND LTAK."SCHEMA" = LTAP."SCHEMA" -- global job
        AND LTAK.MANDT = LTAP.MANDT
        AND LTAK.LGNUM = LTAP.LGNUM
        AND LTAK.TANUM = LTAP.TANUM
    LEFT JOIN T300T AS T300T ON 1=1
        AND T300T."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T300T.MANDT = LTAP.MANDT
        AND T300T.LGNUM = LTAP.LGNUM
        AND T300T.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T301T AS T301T_VON ON 1=1
        AND T301T_VON."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T301T_VON.MANDT = LTAP.MANDT
        AND T301T_VON.LGNUM = LTAP.LGNUM
        AND T301T_VON.LGTYP = LTAP.VLTYP
        AND T301T_VON.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T301T AS T301T_NACH ON 1=1
        AND T301T_NACH."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T301T_NACH.MANDT = LTAP.MANDT
        AND T301T_NACH.LGNUM = LTAP.LGNUM
        AND T301T_NACH.LGTYP = LTAP.NLTYP
        AND T301T_NACH.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T302T AS T302T_VON ON 1=1
        AND T302T_VON."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T302T_VON.MANDT = LTAP.MANDT
        AND T302T_VON.LGNUM = LTAP.LGNUM
        AND T302T_VON.LGTYP = LTAP.VLTYP
        AND T302T_VON.LGBER = LTAP.VLBER
        AND T302T_VON.SPRAS = '<%=primaryLanguageKey%>'  
    LEFT JOIN T302T AS T302T_NACH ON 1=1
        AND T302T_NACH."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T302T_NACH.MANDT = LTAP.MANDT
        AND T302T_NACH.LGNUM = LTAP.LGNUM
        AND T302T_NACH.LGTYP = LTAP.NLTYP
        AND T302T_NACH.LGBER = LTAP.NLBER
        AND T302T_NACH.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T336T AS T336T ON 1=1
        AND T336T."SCHEMA" = LTAP."SCHEMA" -- global job
        AND T336T.MANDT = LTAP.MANDT
        AND T336T.LGNUM = LTAP.LGNUM
        AND T336T.KZDIF = LTAP.KZDIF
        AND T336T.SPRAS = '<%=primaryLanguageKey%>'
    JOIN "SCHEMA_XLSX_MD" AS MAP ON
        MAP.SCHEMA = LTAP.SCHEMA
;
