DROP VIEW IF EXISTS PP_AFKO;

CREATE VIEW PP_AFKO AS
SELECT DISTINCT
     AFKO.*
     , MAP."PRETTY_NAME"
FROM AFKO AS AFKO
    JOIN "SCHEMA_xlsx_MD" as "MAP" on 
        AFKO."SCHEMA" = "MAP"."SCHEMA" -- global job
    INNER JOIN PP_AUFK AS AUFK ON 1=1
        AND AFKO."SCHEMA" = AUFK."SCHEMA"
        AND AFKO.MANDT = AUFK.MANDT
        AND AFKO.AUFNR = AUFK.AUFNR;