INSERT INTO _CEL_PP_ACTIVITIES(
	"_CASE_KEY"
	,"MANDT"
	,"AUFNR"
	,"POSNR"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
    ,"SCHEMA"
    ,"PRETTY_NAME")
SELECT DISTINCT
	A._CASE_KEY
	,A.MANDT
	,A.AUFNR
	,A.POSNR
	,'Fertigungsauftrag angelegt' AS ACTIVITY_DE
	,'Create Production Order' AS ACTIVITY_EN
	,DATE_TRUNC('MINUTES', CAST(A.ERDAT AS DATE) + CAST(A.ERFZEIT AS TIME) ) AS EVENTTIME
	,10000 AS _SORTING
	,CAST(A.ERNAM AS VARCHAR) AS USER_NAME
	,USR02.USTYP AS USER_TYPE
    , A."SCHEMA" AS "SCHEMA"
    , A.PRETTY_NAME
FROM TMP_PP_AUFK_AFKO_AFPO AS A
	LEFT JOIN USR02 AS USR02 ON 1=1
        AND A."SCHEMA" = USR02."SCHEMA"
		AND A.MANDT=USR02.MANDT
		AND A.ERNAM=USR02.BNAME;