DROP VIEW IF EXISTS PP_AUFK;

CREATE VIEW PP_AUFK AS
SELECT DISTINCT
    AUFK.*
	, T001.BUTXT AS BUKRS_TEXT 
    , T001W.NAME1 AS WERK_TEXT
	, TGSBT.GTEXT AS GSBER_TEXT 
--	, CEPCT.KTEXT AS PRCTR_TEXT
    , MAP."PRETTY_NAME"
    , "AFKO"."SFCPF"
FROM AUFK AS AUFK
    JOIN "SCHEMA_xlsx_MD" as "MAP" on 
        AUFK."SCHEMA" = "MAP"."SCHEMA" -- global job
	JOIN AFPO AS AFPO ON 1=1 
		AND AUFK."SCHEMA" = AFPO."SCHEMA"
        AND AUFK.MANDT = AFPO.MANDT
		AND AUFK.AUFNR = AFPO.AUFNR 
	LEFT JOIN T001 AS T001 ON 1=1
		AND T001."SCHEMA"=AUFK."SCHEMA"
        AND T001.MANDT=AUFK.MANDT
		AND T001.BUKRS=AUFK.BUKRS
	LEFT JOIN T001W AS T001W ON 1=1
		AND T001W."SCHEMA"=AUFK."SCHEMA"
        AND T001W.MANDT=AUFK.MANDT
		AND T001W.WERKS=AUFK.WERKS
	LEFT JOIN TGSBT AS TGSBT ON 1=1
		AND TGSBT."SCHEMA"=AUFK."SCHEMA"
        AND TGSBT.MANDT=AUFK.MANDT
		AND TGSBT.GSBER=AUFK.GSBER
		AND TGSBT.SPRAS='<%=primaryLanguageKey%>'
    LEFT JOIN AFKO AS AFKO ON 1=1
		AND AFKO."SCHEMA"= AUFK."SCHEMA"
        AND AFKO.MANDT = AUFK.MANDT
        AND "AFKO"."AUFNR" = "AUFK"."AUFNR"
--	LEFT JOIN CEPCT AS CEPCT ON 1=1
--		AND CEPCT.MANDT=AUFK.MANDT
--		AND CEPCT.PRCTR=AUFK.PRCTR
--		AND CEPCT.KOKRS=AUFK.KOKRS
--		AND CEPCT.DATBI>AUFK.ERDAT
--		AND CEPCT.SPRAS='<%=primaryLanguageKey%>' 
WHERE 1=1 
    AND AUFK.AUTYP IN <%=orderCategories%>;