INSERT INTO _CEL_PP_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"AUFNR"
	,"POSNR"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
    , "SCHEMA"
    ,"PRETTY_NAME")
SELECT DISTINCT 
	A._CASE_KEY
	,A.MANDT
	,A.AUFNR
	,A.POSNR
	,'Tatsächlicher Fertigungsbeginn' AS ACTIVITY_DE
	,'Actual start time' AS ACTIVITY_EN
	,CAST(A.GSTRI AS DATE) + CAST(A.GSUZI AS TIME)  AS "EVENTTIME" 
	,29000 AS _SORTING
	,CAST(A.ERNAM AS VARCHAR) AS USER_NAME
	,USR02.USTYP AS USER_TYPE
    , A."SCHEMA" AS "SCHEMA"
    ,"PRETTY_NAME" AS "PRETTY_NAME"
FROM TMP_PP_AUFK_AFKO_AFPO AS A
	LEFT JOIN USR02 AS USR02 ON 1=1
        AND A.SCHEMA = USR02.SCHEMA
		AND A.MANDT=USR02.MANDT
		AND A.ERNAM=USR02.BNAME
WHERE 1=1
	AND A.GSTRI IS NOT NULL 
	AND A.GSUZI IS NOT NULL ;