INSERT INTO _CEL_PP_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"AUFNR"
	,"POSNR"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
    , "SCHEMA"
    , "PRETTY_NAME")
SELECT DISTINCT
	A._CASE_KEY
	,A.MANDT
	,A.AUFNR
	,A.POSNR
	,'Tatsächliches Fertigungsende' AS "ACTIVITY_DE"
	,'Actual finish time' AS "ACTIVITY_EN"
	,CASE -- sometimes the field AFPO.LTRMI is used instead of the field AFKO.GLTRI 
		WHEN A.GLTRI IS NOT NULL THEN
			CASE 
			WHEN A.GEUZI IS NOT NULL THEN CAST(A.GLTRI AS DATE) + CAST(A.GEUZI AS TIME) 
			ELSE CAST(A.GLTRI AS DATE) + CAST('23:59:59' AS TIME)
			END  
		ELSE CAST(A.LTRMI AS DATE) + CAST('23:59:59' AS TIME)
	  END AS EVENTTIME
	,41000 AS "_SORTING"
	,CAST(A.ERNAM AS VARCHAR) AS USER_NAME
	, USR02.USTYP AS USER_TYPE
    , A."SCHEMA" AS "SCHEMA"
    , A."PRETTY_NAME" AS "PRETTY_NAME"
FROM TMP_PP_AUFK_AFKO_AFPO AS A
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND A.SCHEMA=USR02.SCHEMA
        AND A.MANDT=USR02.MANDT
		AND A.ERNAM=USR02.BNAME
WHERE 1=1 
    AND ((A.GLTRI IS NOT NULL) OR (A.LTRMI IS NOT NULL));