DROP VIEW IF EXISTS PP_AFVV;

CREATE VIEW PP_AFVV AS
SELECT DISTINCT
     AFVV.*
FROM PP_AFRU AS AFRU
    JOIN "SCHEMA_xlsx_MD" as "MAP" on 
        AFRU."SCHEMA" = "MAP"."SCHEMA" -- global job
	JOIN AFVV AS AFVV ON 1=1
        AND AFRU."SCHEMA" = AFVV."SCHEMA"
    	AND AFRU.MANDT = AFVV.MANDT
    	AND AFRU.AUFPL = AFVV.AUFPL
    	AND AFRU.APLZL = AFVV.APLZL;