DROP VIEW IF EXISTS PP_CRHD;
								
CREATE VIEW PP_CRHD AS
SELECT DISTINCT 
	 CRHD.* 
	,CRTX.KTEXT AS ARBPL_TEXT
    , MAP."PRETTY_NAME" AS "PRETTY_NAME"
FROM CRHD AS CRHD
    JOIN "SCHEMA_XLSX_MD" as "MAP" on -- global job
        CRHD."SCHEMA" = "MAP"."SCHEMA"
	JOIN CRTX AS CRTX ON 1=1
		AND CRTX."SCHEMA" = CRHD."SCHEMA"
        AND CRTX.MANDT = CRHD.MANDT
		AND CRTX.OBJID = CRHD.OBJID
		AND CRTX.OBJTY = CRHD.OBJTY
		AND CRTX.SPRAS = '<%=primaryLanguageKey%>';