INSERT INTO _CEL_PP_ACTIVITIES (
	"_CASE_KEY"
	,"MANDT"
	,"AUFNR"
	,"POSNR"
	,"ACTIVITY_DE"
	,"ACTIVITY_EN"
	,"ACTIVITY_DETAIL_DE"
	,"ACTIVITY_DETAIL_EN"
	,"EVENTTIME"
	,"_SORTING"
	,"USER_NAME"
	,"USER_TYPE"
    , "SCHEMA"
    , PRETTY_NAME)
SELECT DISTINCT
	A._CASE_KEY
	,A.MANDT
	,A.AUFNR
	,A.POSNR
	,T156T_DE.BTEXT AS ACTIVITY_DE
	,T156T_EN.BTEXT AS ACTIVITY_EN
	,T003T_DE.LTEXT AS ACTIVITY_DETAIL_DE
	,T003T_EN.LTEXT AS ACTIVITY_DETAIL_EN
	,CAST(MKPF.CPUDT AS DATE) + COALESCE(CAST(MKPF.CPUTM AS TIME),CAST('00:00:00' AS TIME)) AS EVENTTIME -- time of entry
	,42000 AS SORTING 
	,MKPF.USNAM AS USER_NAME 
	,USR02.USTYP AS USER_TYPE
    , A."SCHEMA" AS "SCHEMA"
    , A."PRETTY_NAME" AS "PRETTY_NAME"
FROM TMP_PP_AUFK_AFKO_AFPO AS A
	JOIN AUFM AS AUFM ON 1=1
        AND AUFM."SCHEMA" = A."SCHEMA"
		AND AUFM.MANDT = A.MANDT
		AND AUFM.AUFNR = A.AUFNR
	JOIN MSEG AS MSEG ON 1=1 
        AND AUFM."SCHEMA" = A."SCHEMA"
		AND AUFM.MANDT = MSEG.MANDT
		AND AUFM.MBLNR = MSEG.MBLNR
		AND AUFM.MJAHR = MSEG.MJAHR
		AND AUFM.ZEILE = MSEG.ZEILE
	JOIN MKPF AS MKPF ON 1=1 
        AND MKPF."SCHEMA" = MSEG."SCHEMA"
		AND MKPF.MANDT = MSEG.MANDT
		AND MKPF.MBLNR = MSEG.MBLNR
		AND MKPF.MJAHR = MSEG.MJAHR
	LEFT JOIN T156T AS T156T_EN ON 1=1
        AND T156T_EN."SCHEMA" = MSEG."SCHEMA"
		AND T156T_EN.MANDT = MSEG.MANDT
		AND T156T_EN.BWART = MSEG.BWART
		AND COALESCE(MSEG.SOBKZ,'') = COALESCE(T156T_EN.SOBKZ,'')
		AND COALESCE(MSEG.KZBEW,'') = COALESCE(T156T_EN.KZBEW,'')
		AND COALESCE(MSEG.KZZUG,'') = COALESCE(T156T_EN.KZZUG,'')
		AND COALESCE(MSEG.KZVBR,'') = COALESCE(T156T_EN.KZVBR,'')
		AND T156T_EN.SPRAS = 'E'
	LEFT JOIN T156T AS T156T_DE ON 1=1 
        AND T156T_DE."SCHEMA" = MSEG."SCHEMA"
		AND T156T_DE.MANDT = MSEG.MANDT
		AND T156T_DE.BWART = MSEG.BWART
		AND COALESCE(MSEG.SOBKZ,'') = COALESCE(T156T_DE.SOBKZ,'')
		AND COALESCE(MSEG.KZBEW,'') = COALESCE(T156T_DE.KZBEW,'')
		AND COALESCE(MSEG.KZZUG,'') = COALESCE(T156T_DE.KZZUG,'')
		AND COALESCE(MSEG.KZVBR,'') = COALESCE(T156T_DE.KZVBR,'')
		AND T156T_DE.SPRAS = 'D'
	LEFT JOIN T003T AS T003T_EN ON 1=1
        AND T003T_EN."SCHEMA" = MKPF."SCHEMA"
		AND T003T_EN.MANDT = MKPF.MANDT
		AND T003T_EN.BLART = MKPF.BLART
		AND T003T_EN.SPRAS = 'E'
	LEFT JOIN T003T AS T003T_DE ON 1=1 
		AND T003T_DE."SCHEMA" = MKPF."SCHEMA"
        AND T003T_DE.MANDT = MKPF.MANDT
		AND T003T_DE.BLART = MKPF.BLART
		AND T003T_DE.SPRAS = 'D'
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND USR02."SCHEMA" = MKPF."SCHEMA"
        AND USR02.MANDT = MKPF.MANDT
		AND USR02.BNAME = MKPF.USNAM

WHERE MSEG.BWART in ('101', '102', '261' ) -- changed from T156T to MSEG (potentially empty left join, if Language key not maintained)
;
-- Erster/Letzter Wareneingang --> BWART 101 
-- Storno könnte interessant sein --> BWART 102
-- Erste/Letzte Materialentnahme --> BWART 261
