DROP VIEW IF EXISTS PP_AFPO;

CREATE VIEW PP_AFPO AS
SELECT DISTINCT
     AFPO.*
	 ,MAKT.MAKTX AS MATNR_TEXT -- Material type
	 ,T023T.WGBEZ AS MATKL_TEXT -- Material group 
     ,CASE 
		WHEN AUFK.WAERS = '<%=currency%>' THEN MBEW.STPRS*IFNULL(TCURX.TDEC,1) 
        WHEN TCURR_CC.UKURS > 0 THEN (MBEW.STPRS*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS < 0 THEN (MBEW.STPRS*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
	  END AS STPRS_CONVERTED
     , MAP."PRETTY_NAME"
     ,AFPO.MANDT || AFPO.AUFNR || AFPO.POSNR AS "_CASE_KEY"
FROM AFPO AS AFPO
    JOIN "SCHEMA_xlsx_MD" as "MAP" on 
        AFPO."SCHEMA" = "MAP"."SCHEMA" -- global job
	JOIN PP_AUFK AS AUFK ON 1=1 
		AND AFPO."SCHEMA"=AUFK."SCHEMA"
        AND AFPO.MANDT=AUFK.MANDT
		AND AFPO.AUFNR=AUFK.AUFNR
    LEFT JOIN MBEW AS MBEW ON 1=1 
		AND AFPO."SCHEMA"=MBEW."SCHEMA"
        AND AFPO.MATNR=MBEW.MATNR 
		AND AFPO.MANDT=MBEW.MANDT 
        AND AFPO.DWERK = MBEW.BWKEY
		AND COALESCE(AFPO.BWTAR, 'BWTAR')=COALESCE(MBEW.BWTAR,'BWTAR')
	LEFT JOIN MAKT AS MAKT ON 1=1
    	AND AFPO."SCHEMA" = MAKT."SCHEMA"
        AND AFPO.MANDT = MAKT.MANDT
		AND AFPO.MATNR = MAKT.MATNR 
		AND MAKT.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN MARA ON 1=1   
        AND AFPO."SCHEMA"=MARA."SCHEMA" 
		AND AFPO.MANDT=MARA.MANDT
		AND AFPO.MATNR=MARA.MATNR
    LEFT JOIN T023T AS T023T ON 1=1 
		AND T023T."SCHEMA"=MARA."SCHEMA"
        AND T023T.MANDT=MARA.MANDT
		AND T023T.MATKL=MARA.MATKL
		AND T023T.SPRAS='<%=primaryLanguageKey%>'
    LEFT JOIN TCURR_CC AS TCURR_CC ON 1=1
	    AND TCURR_CC."SCHEMA" = AFPO."SCHEMA"
        AND TCURR_CC.MANDT = AFPO.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = AUFK.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND CAST(AUFK.ERDAT AS DATE) >= TCURR_CC.VALID_START 
        AND CAST(AUFK.ERDAT AS DATE) < TCURR_CC.VALID_END
	LEFT JOIN TCURF_CC AS TCURF_CC ON 1=1
	    AND AFPO."SCHEMA" = TCURF_CC."SCHEMA"
        AND AFPO.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
        AND CAST(AUFK.ERDAT AS DATE) >= TCURF_CC.VALID_START 
        AND CAST(AUFK.ERDAT AS DATE) < TCURF_CC.VALID_END
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		--AND TCURR_CC."SCHEMA" = TCURX."SCHEMA"
        AND TCURR_CC.FCURR = TCURX.CURRKEY;