DROP VIEW IF EXISTS PP_PLPO;

CREATE VIEW PP_PLPO AS
SELECT DISTINCT
     PLPO.*
     , MAP."PRETTY_NAME"
FROM PP_AFVC AS AFVC
    JOIN "SCHEMA_XLSX_MD" as "MAP" on -- global job
        AFVC."SCHEMA" = "MAP"."SCHEMA"
	JOIN PLPO AS PLPO ON 1=1
		AND AFVC."SCHEMA" = PLPO."SCHEMA"
        AND AFVC.MANDT = PLPO.MANDT
		AND AFVC.PLNTY = PLPO.PLNTY
		AND AFVC.PLNNR = PLPO.PLNNR
		AND AFVC.PLNKN = PLPO.PLNKN
		AND AFVC.ZAEHL = PLPO.ZAEHL;