-- Help Table for insert, for  Multi Client System
DROP TABLE IF EXISTS "LH_DD02T";
Create Table "LH_DD02T" as
Select "TABNAME", "DDLANGUAGE", "DDTEXT" FROM (
Select 	"TABNAME" AS "TABNAME",
	"DDLANGUAGE" AS "DDLANGUAGE",
	"DDTEXT" AS "DDTEXT",
    ROW_NUMBER() OVER (PARTITION BY "TABNAME","DDLANGUAGE" ORDER BY "DDTEXT" asc) AS "ROW_NUM"
FROM 
	"DD02T" where DDLANGUAGE in ('E','D')
) as "HELP" where "ROW_NUM" = 1;


DROP TABLE IF EXISTS PP_NAME_MAPPING_TABLES;

CREATE TABLE PP_NAME_MAPPING_TABLES AS
SELECT
	DD02T.TABNAME AS TABLE_NAME,
	DD02T.DDLANGUAGE AS LANGUAGE,
	DD02T.DDTEXT AS PRETTY_NAME
FROM
	"LH_DD02T"  as "DD02T"-- globale Anpassung
	
UNION
 
SELECT
	'_CEL_P2P_ACTIVITIES',
	'D',
	'Aktivitäten'
	
UNION

SELECT
	'_CEL_P2P_ACTIVITIES',
	'E',
	'Activities'
;

-- Housekeeping Prozess
DROP TABLE IF EXISTS "LH_DD02T";


/*
Old Logic

DROP VIEW IF EXISTS PP_NAME_MAPPING_TABLES;

CREATE VIEW PP_NAME_MAPPING_TABLES AS
SELECT
	DD02T.TABNAME AS TABLE_NAME,
	DD02T.DDLANGUAGE AS LANGUAGE,
	DD02T.DDTEXT AS PRETTY_NAME
FROM
	DD02T
	
UNION
 
SELECT
	'_CEL_PP_ACTIVITIES',
	'D',
	'Aktivitäten'
	
UNION

SELECT
	'_CEL_PP_ACTIVITIES',
	'E',
	'Activities'
;

*/