DROP VIEW IF EXISTS PP_MARA;	
		
CREATE VIEW PP_MARA AS
SELECT DISTINCT
     MARA.*
     , MAP."PRETTY_NAME" -- global job
FROM MARA
    JOIN "SCHEMA_xlsx_MD" as "MAP" on 
        MARA."SCHEMA" = "MAP"."SCHEMA" -- global job
INNER JOIN MARC ON 1=1
    AND MARC."SCHEMA" = MARA."SCHEMA" -- global job
    AND MARC.MATNR = MARA.MATNR
    AND MARC.MANDT = MARA.MANDT
INNER JOIN PP_AFPO AS AFPO ON 1=1
    AND AFPO."SCHEMA" = MARC."SCHEMA" -- global job
    AND AFPO.MATNR = MARC.MATNR
    AND AFPO.MANDT = MARC.MANDT
    AND AFPO.DWERK = MARC.WERKS;