DROP VIEW IF EXISTS PP_MARC;

CREATE VIEW PP_MARC AS
SELECT DISTINCT
     MARC.*
     , MAP."PRETTY_NAME"
FROM MARC
JOIN "SCHEMA_XLSX_MD" as "MAP" on -- global job
    MARC."SCHEMA" = "MAP"."SCHEMA"
INNER JOIN PP_AFPO AS AFPO ON 1=1
    AND AFPO."SCHEMA" = MARC."SCHEMA"
    AND AFPO.MATNR = MARC.MATNR
    AND AFPO.MANDT = MARC.MANDT
    AND AFPO.DWERK = MARC.WERKS
WHERE MARC.WERKS IN (SELECT T001W.WERKS
				       FROM T001K
				            JOIN T001W ON 1=1
					            AND T001K."SCHEMA" = T001W."SCHEMA"
                                AND T001K.BWKEY = T001W.BWKEY);