/*DESCRIPTION:
1. Transformation Description:
This transformation creates an activity with the following name: Delete Delivery Note







2. Required Tables:
CDHDR
CDPOS
TMP_O2C_VBAK_VBAP
USR02

3. Required Columns:
CDHDR.CHANGENR
CDHDR.LTRIM
CDHDR.MANDANT
CDHDR.NOW
CDHDR.OBJECTCLAS
CDHDR.OBJECTID
CDHDR.TCODE
CDHDR.UDATE
CDHDR.USERNAME
CDHDR.UTIME
CDHDR.VALUE_NEW
CDPOS.CHANGENR
CDPOS.CHNGIND
CDPOS.FNAME
CDPOS.MANDANT
CDPOS.OBJECTCLAS
CDPOS.OBJECTID
CDPOS.TABKEY
CDPOS.TABNAME
CDPOS.VALUE_NEW
...
Contact App Store support for the complete list.

4. Columns used for timestamp:
CDHDR.UDATE
CDHDR.UTIME

5. Parameters used in where clause:
None

6. Parameters used in joins:
None
*/
INSERT INTO _CEL_O2C_ACTIVITIES (
    "SCHEMA", -- global job
    "PRETTY_NAME", -- global job
    "SC/PC", -- global job
	"_CASE_KEY",
	"ACTIVITY_DE",
	"ACTIVITY_EN",
	"EVENTTIME",
	"_SORTING",
	"USER_NAME",
	"USER_TYPE",
	"CHANGED_TABLE",
	"CHANGED_FIELD",
	"CHANGED_FROM",
	"CHANGED_TO",
	"CHANGE_NUMBER",
	"TRANSACTION_CODE",
	"MANDT",
	"VBELN",
	"POSNR",
    "_ACTIVITY_KEY")
SELECT
    V_ORDERS."SCHEMA", -- global job
    V_ORDERS."PRETTY_NAME", -- global job
    V_ORDERS."SC/PC", -- global job
	V_ORDERS._CASE_KEY AS _CASE_KEY
	,'Lösche Lieferschein'AS  "ACTIVITY_DE"
	,'Delete Delivery Note' AS  "ACTIVITY_EN"
	,CAST(CDHDR.UDATE AS DATE) + CAST(ISNULL(CAST(CDHDR.UTIME AS TIME), '23:59:59') AS TIME) AS "EVENTTIME"
	,64 AS "_SORTING"
	,CDHDR.USERNAME AS "USER_NAME"
	,USR02.USTYP AS "USER_TYPE"
	,CDPOS.TABNAME AS "CHANGED_TABLE"
	,CDPOS.FNAME AS "CHANGED_FIELD"
	,LTRIM(CDPOS.VALUE_OLD) AS "CHANGED_FROM"
	,LTRIM(CDPOS.VALUE_NEW) AS "CHANGED_TO"
	,CDPOS.CHANGENR AS "CHANGE_NUMBER"
	,CDHDR.TCODE AS "TRANSACTION_CODE"
	,V_ORDERS.MANDT AS "MANDT"
	,V_ORDERS.VBELN AS "VBELN"
	,V_ORDERS.POSNR AS "POSNR"
    ,V_ORDERS."PRETTY_NAME"||CDHDR."MANDANT" || CDHDR."OBJECTCLAS" || CDHDR."OBJECTID" || CDHDR."CHANGENR" AS "_ACTIVITY_KEY" -- global job
FROM
	TMP_O2C_VBAK_VBAP AS V_ORDERS
	JOIN CDPOS AS CDPOS ON 1=1
        AND "CDPOS"."SCHEMA" = "V_ORDERS"."SCHEMA" -- global job
	    AND CDPOS.MANDANT = V_ORDERS.MANDT
	    AND CDPOS.TABKEY = "V_ORDERS"."MANDT" || "V_ORDERS"."VBELN" || "V_ORDERS"."POSNR" -- globale Anpasssung, da vorher über V_ORDERS.CASE_KEY gegangen wurde
        AND CDPOS.CHNGIND = 'U'
        AND CDPOS.FNAME = 'LFSTK' --'LFSTA'
        AND CDPOS.VALUE_OLD = 'C' AND VALUE_NEW = 'A'
        AND CDPOS.TABNAME = 'VBUK' --'VBUP'
	JOIN CDHDR AS CDHDR ON 1=1 
        AND "CDPOS"."SCHEMA" = "CDHDR"."SCHEMA" -- global job
		AND CDPOS.MANDANT = CDHDR.MANDANT
		AND CDPOS.OBJECTCLAS = CDHDR.OBJECTCLAS
		AND CDPOS.OBJECTID = CDHDR.OBJECTID
		AND CDPOS.CHANGENR = CDHDR.CHANGENR
	LEFT JOIN USR02 AS USR02 ON 1=1
        AND "USR02"."SCHEMA" = "CDHDR"."SCHEMA" -- global job
		AND USR02.MANDT = CDHDR.MANDANT
		AND USR02.BNAME = CDHDR.USERNAME
;