DROP TABLE IF EXISTS TMP_LIPS;
CREATE TABLE TMP_LIPS AS(
    SELECT DISTINCT
            MAP.*, -- global job
            VBFA.MANDT,
            VBFA.VBELV AS VBELN,
            VBFA.POSNV AS POSNR,
            SUM(LIPS.LFIMG) AS "SUM_LFIMG"
		FROM O2C_VBFA_V AS VBFA
        JOIN "SCHEMA_xlsx_MD" as "MAP" ON 
            VBFA."SCHEMA" = MAP."SCHEMA" -- global job
        JOIN LIPS AS LIPS ON 1=1
	    	AND	VBFA.MANDT = LIPS.MANDT
        	AND VBFA.VBELN = LIPS.VBELN
        	AND VBFA.POSNN = LIPS.POSNR
            AND VBFA."SCHEMA" = LIPS."SCHEMA" -- global Job
		GROUP BY VBFA.MANDT,VBFA.VBELV,VBFA.POSNV, MAP."SCHEMA", MAP."PRETTY_NAME", MAP."SC/PC", MAP._CELONIS_CHANGE_DATE -- (VBFA.SCHEMA, MAP."PRETTY_NAME" Global Job)
);

DROP TABLE IF EXISTS TMP_VBRP;
CREATE TABLE TMP_VBRP AS(
    SELECT DISTINCT
            MAP.*, -- global job
            VBFA.MANDT,
            VBFA.VBELV AS VBELN,
            VBFA.POSNV AS POSNR,
            SUM(VBRP.FKIMG) AS "SUM_FKIMG",
            SUM(VBRP.NETWR) AS "SUM_NETWR"
		FROM O2C_VBFA_V AS VBFA
        JOIN "SCHEMA_xlsx_MD" as "MAP" ON 
            VBFA."SCHEMA" = MAP."SCHEMA" -- global job
        JOIN VBRP AS VBRP ON 1=1
            AND VBFA."SCHEMA" = VBRP."SCHEMA" -- global job
	    	AND	VBFA.MANDT = VBRP.MANDT
        	AND VBFA.VBELN = VBRP.VBELN
        	AND VBFA.POSNN = VBRP.POSNR
		GROUP BY VBFA.MANDT,VBFA.VBELV,VBFA.POSNV, MAP."SCHEMA",MAP."PRETTY_NAME", MAP."SC/PC", MAP._CELONIS_CHANGE_DATE -- (MAP."PRETTY_NAME", VBFA.SCHEMA Global Job)
);