DROP TABLE IF EXISTS "O2C_NAME_MAPPING_TABLES";

-- Help Table for insert, for  Multi Client System
DROP TABLE IF EXISTS "LH_DD02T";
Create Table "LH_DD02T" as
Select "TABNAME", "DDLANGUAGE", "DDTEXT" FROM (
Select 	"TABNAME" AS "TABNAME",
	"DDLANGUAGE" AS "DDLANGUAGE",
	"DDTEXT" AS "DDTEXT",
    ROW_NUMBER() OVER (PARTITION BY "TABNAME","DDLANGUAGE" ORDER BY "DDTEXT" asc) AS "ROW_NUM"
FROM 
	"DD02T" where DDLANGUAGE in ('E','D')
) as "HELP" where "ROW_NUM" = 1;



CREATE TABLE "O2C_NAME_MAPPING_TABLES" AS
SELECT 
	"LH_DD02T"."TABNAME" AS "TABLE_NAME", -- globale Anpassung
	"LH_DD02T"."DDLANGUAGE" AS "LANGUAGE", -- globale Anpassung
    	"LH_DD02T"."DDTEXT" AS "PRETTY_NAME" -- globale Anpassung
FROM
	"LH_DD02T" -- globale Anpassung
	
UNION
 
SELECT
	'_CEL_O2C_ACTIVITIES',
	'D',
	'Aktivitäten'
	
UNION

SELECT
	'_CEL_O2C_ACTIVITIES',
	'E',
	'Activities';

-- Cleaning und Housekeeping Prozess
DROP TABLE IF EXISTS "LH_DD02T";

/*
UPDATE _CEL_O2C_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_EN = NM.PRETTY_NAME
FROM O2C_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'E';

UPDATE _CEL_O2C_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_DE = NM.PRETTY_NAME
FROM O2C_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'D';
 */